Added forum functionality
pydis-codejam-2020-observant-otters/summer-code-jam-2020 pull request #5
Opened 2020-08-04 18:47 UTC by SansPapyrus683

you can actually make new threads and post messages and stuff
but now we have to implement editing and deleting crap
oh god

2020-08-04 20:03 UTC, qxzcode submitted a review, later dismissed

2020-08-05 03:52 UTC, qxzcode submitted a review, later dismissed

2020-08-07 01:04 UTC, qxzcode requested changes

2020-08-07 01:04 UTC, qxzcode commented on observant-otters/forumthing/forumthing/settings.py
> +DISCORD_CLIENT_SECRET = "sS4161QABYmDEj0X_d4E8bXlXiyi8cMb"
How come these secrets have been committed to the repo again?

2020-08-07 01:18 UTC, SansPapyrus683 commented on observant-otters/forumthing/forumthing/settings.py
> +DISCORD_CLIENT_SECRET = "sS4161QABYmDEj0X_d4E8bXlXiyi8cMb"
yeah sorry did that on accident

2020-08-07 01:26 UTC, qxzcode approved these changes

2020-08-07 08:56 UTC, LiteralGenie approved these changes

2020-08-07 18:08 UTC, merged